name: deploy 
on:
    pull_request: 
        types:
            - closed

jobs:
    deploy: 
        runs-on: ubuntu-latest  
        if: github.event.pull_request.merged == true
        steps:
            - uses: actions/checkout@v4
            - run: |
                    echo "${{ secrets.EC2_KEY }}" > private_key.pem
                    chmod 600 private_key.pem
            - run: |
                ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
                    cd ${{ secrets.EC2_REPO_PATH }}
                    git reset --hard origin/main  # Ensure clean state
                    git pull origin main  # Pull latest changes
                    
                    source env/bin/activate  # Activate virtual environment
                    # pip install -r requirements.txt  # Install dependencies if needed 
                    
                    pm2 restart fastapi-app
                EOF
