name: deploy 
on:
    pull_request: 
        types:
            - closed

jobs:
    deploy: 
        runs-on: ubuntu-latest  
        if: github.event.pull_request.merged == true
        steps:
            - uses: actions/checkout@v4
            - run: |
                    echo "${{ secrets.EC2_KEY }}" > private_key.pem
                    chmod 600 private_key.pem
            - run: |
                ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
                    cd ${{ secrets.EC2_REPO_PATH }}
                    find . -name "*.pyc" -delete
                    git reset --hard origin/main  # Ensure clean state
                    git pull origin main  # Pull latest changes
                    source env/bin/activate  # Activate virtual environment 
                    pm2 stop fastapi-app
                    pm2 delete fastapi-app
                    pm2 flush
                    pm2 start "python -m uvicorn main:app --host 127.0.0.1 --port 8000 --workers 4" --name fastapi-app 
                EOF
