name: test
on:
  pull_request:
    types: 
      - opened
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest 
    strategy: 
      matrix:
        python-version: ["3.13.0"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
        with: 
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: | 
          pwd
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip httpx pytest pytest-md pytest-emoji
      - uses: pavelzw/pytest-action@v2 
        with: 
          emoji: false 
          verbose: false 
          job-summary: true
